project_id = "xqskistgkihlewsxanib"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.imap-connect]
verify_jwt = true

[functions.imap-fetch]
verify_jwt = true

[functions.imap-apply-actions]
verify_jwt = true

